# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:50:24+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class ThreadPoolInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availableCompletionThreads: Optional[int] = None
    availableWorkerThreads: Optional[int] = None
    maxCompletionThreads: Optional[int] = None
    maxWorkerThreads: Optional[int] = None
    minCompletionThreads: Optional[int] = None
    minWorkerThreads: Optional[int] = None
    occupiedCompletionThreads: Optional[int] = None
    occupiedWorkerThreads: Optional[int] = None
